fixtures:
    forge_modules:
        stdlib:
            repo: 'puppetlabs-stdlib'
            ref:  '4.3.2'
        concat:
            repo: 'puppetlabs-concat'
            ref:  '1.1.2'
        nodejs:
            repo: 'puppetlabs-nodejs'
            ref:  '0.4.0'
        postgresql:
            repo: 'puppetlabs-postgresql'
            ref:  '4.1.0' 
        vcsrepo:
            repo: 'puppetlabs-vcsrepo'
            ref: '1.2.0'
        wget:
            repo: 'maestrodev-wget'
            ref: '1.5.6'
        conzar:
            repo: 'conzar-check_run'
            ref: '0.2.3'
    symlinks:
        puppet: "#{source_dir}"
