---
branches:
  only:
  - master
language: ruby
rvm:
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
notifications:
  email: false
